// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDukWXOa-JvlutWaAVifgAxG_-2iMEkH_s',
    appId: '1:583463946398:web:47ceceda7dffb12c25138f',
    messagingSenderId: '583463946398',
    projectId: 'iotproject-7f7d4',
    authDomain: 'iotproject-7f7d4.firebaseapp.com',
    storageBucket: 'iotproject-7f7d4.appspot.com',
    measurementId: 'G-J32B6B43GY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6HoC6uSJwnJjMsT-Uf-ktOyTkthSfDIU',
    appId: '1:583463946398:android:4b6ca4ce50e1599325138f',
    messagingSenderId: '583463946398',
    projectId: 'iotproject-7f7d4',
    storageBucket: 'iotproject-7f7d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT5kdlGh5nSVgjtZQDvIanUzwYorUnhWc',
    appId: '1:583463946398:ios:ff95d083d803fc1825138f',
    messagingSenderId: '583463946398',
    projectId: 'iotproject-7f7d4',
    storageBucket: 'iotproject-7f7d4.appspot.com',
    iosClientId: '583463946398-0r8irolkb75gdp8rkqatl5o27ep6ieul.apps.googleusercontent.com',
    iosBundleId: 'com.example.alarmapps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT5kdlGh5nSVgjtZQDvIanUzwYorUnhWc',
    appId: '1:583463946398:ios:ff95d083d803fc1825138f',
    messagingSenderId: '583463946398',
    projectId: 'iotproject-7f7d4',
    storageBucket: 'iotproject-7f7d4.appspot.com',
    iosClientId: '583463946398-0r8irolkb75gdp8rkqatl5o27ep6ieul.apps.googleusercontent.com',
    iosBundleId: 'com.example.alarmapps',
  );
}
